module.exports = {
    'Aquaculture and Fisheries Science': 'AFS',
    'American Studies': 'AME',
    'Applied Mathematical Sciences': 'AMS',
    'Anthropology': 'APG',
    'Arabic': 'ARB',
    'Art': 'ART',
    'Astronomy': 'AST',
    'Animal and Veterinary Science': 'AVS',
    'Biological and Environmental Studies': 'BES',
    'Biological Sciences': 'BIO',
    'Bachelor of Interdisciplinary Studies': 'BIS',
    'Biomedical Engineering': 'BME',
    'Biomedical and Pharmaceutical Sciences': 'BPS',
    'Business': 'BUS',
    'Criminal Justice System': 'CCJ',
    'Chemical Engineering': 'CHE',
    'Chemistry': 'CHM',
    'Chinese': 'CHN',
    'Classics': 'CLA',
    'Comparative Literature Studies': 'CLS',
    'Communicative Disorders': 'CMD',
    'Communication Studies': 'COM',
    'Community Planning': 'CPL',
    'Graduate Continuous Registration': 'CRG',
    'Computer Science': 'CSC',
    'Digital Forensics and Cyber Security': 'CSF',
    'Community Service': 'CSV',
    'Civil and Environmental Engineering': 'CVE',
    'Economics': 'ECN',
    'Education': 'EDC',
    'Ph.D. in Education': 'EDP',
    'Special Education': 'EDS',
    'Environmental Economics': 'EEC',
    'Engineering': 'EGR',
    'Electrical Engineering': 'ELE',
    'English Language Studies': 'ELS',
    'English': 'ENG',
    'Entomology': 'ENT',
    'Environmental Sciences': 'EVS',
    'Film Media': 'FLM',
    'Forensic Science': 'FOS',
    'French': 'FRN',
    'Grand Challenges': 'GCH',
    'Geography': 'GEG',
    'Geosciences': 'GEO',
    'German': 'GER',
    'Greek': 'GRK',
    'Gender and Women\'s Studies': 'GWS',
    'Hebrew': 'HBW',
    'Human Development and Family Studies': 'HDF',
    'History': 'HIS',
    'Health': 'HLT',
    'Honors Program': 'HPR',
    'Health Services Administration': 'HSA',
    'Human Science and Services': 'HSS',
    'Industrial and Systems Engineering': 'ISE',
    'Italian': 'ITL',
    'Internships and Experiential Education': 'ITR',
    'Journalism': 'JOR',
    'Japanese': 'JPN',
    'Kinesiology': 'KIN',
    'Languages': 'LAN',
    'Landscape Architecture': 'LAR',
    'Latin American Studies': 'LAS',
    'Latin': 'LAT',
    'Letters': 'LET',
    'Library': 'LIB',
    'Linguistics': 'LIN',
    'Labor Relations and Human Resources': 'LRS',
    'Library and Information Studies': 'LSC',
    'Master of Science in Accounting': 'MAC',
    'Marine Affairs': 'MAF',
    'Master’s in Business Administration': 'MBA',
    'Mechanical Engineering': 'MCE',
    'Microbiology': 'MIC',
    'Medical Laboratory Science': 'MLS',
    'Military Science and Leadership': 'MSL',
    'Mathematics': 'MTH',
    'Music': 'MUS',
    'New England Studies': 'NES',
    'Neuroscience': 'NEU',
    'Nutrition and Food Sciences': 'NFS',
    'Natural Resources Science': 'NRS',
    'Nuclear Engineering': 'NUE',
    'Nursing': 'NUR',
    'Nonviolence and Peace Studies': 'NVP',
    'Oceanography': 'OCG',
    'Undergraduate Off Campus Study': 'OCG',
    'Graduate Off Campus Study': 'OCSG',
    'Pharmacy': 'PHC',
    'Philosophy': 'PHL',
    'Pharmacy Practice': 'PHP',
    'Physical Therapy': 'PHT',
    'Physics': 'PHY',
    'Prior Learning Assessment': 'PLA',
    'Plant Sciences': 'PLS',
    'Portuguese': 'POR',
    'Public Relations': 'PRS',
    'Political Science': 'PSC',
    'Psychology': 'PSY',
    'Resource Development Education': 'RDE',
    'Joint Ph.D. Program with Rhode Island College': 'RIC',
    'Religious Studies': 'RLS',
    'Russian': 'RUS',
    'School of Communications and Media': 'SCM',
    'Sociology': 'SOC',
    'Spanish': 'SPA',
    'Statistics': 'STA',
    'Sustainability': 'SUS',
    'Theatre': 'THE',
    'Thanatology': 'THN',
    'Textiles, Fashion Merchandising, and Design': 'TMD',
    'University College for Academic Success': 'UCS',
    'Urban Affairs': 'URB',
    'University of Rhode Island Freshman Seminar': 'URI',
    'Writing': 'WRT',
    'Ocean Engineering': 'OCE',
    'Biochemistry': 'BCH',
    'Africana Studies': 'AAF',
    'Art History': 'ARH',

}
